### Sign up
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}

### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}

### Sign out
POST http://localhost:3000/auth/signout

### Find current user
GET http://localhost:3000/auth/self

### Find a user with given id
GET http://localhost:3000/auth/5

### Find users with given email
GET http://localhost:3000/auth?email=baoha3605@gmail.com

### Update user with given id
PATCH  http://localhost:3000/auth/2
content-type: application/json

{
    "password": "123"
}

### Remove user with given id
DELETE   http://localhost:3000/auth/5